# Generated by Django 5.2.3 on 2025-07-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('recipient', models.CharField(blank=True, max_length=255)),
                ('date_shipped', models.DateField()),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
    ]
