# Generated by Django 5.2.3 on 2025-07-06 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('outbound', '0002_outboundrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('recipient', models.CharField(max_length=255)),
                ('date_shipped', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_entries', to='inventory.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='outboundentry',
            name='product',
        ),
        migrations.DeleteModel(
            name='OutboundRecord',
        ),
        migrations.DeleteModel(
            name='OutboundEntry',
        ),
    ]
